apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-{{ .Values.environment }}
spec:
  acme:
    server: {{ template "server-address" . }}
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: letsencrypt-{{ .Values.environment }}
    http01: {}