kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-propagator
subjects:
- kind: ServiceAccount
  name: secret-propagator
  namespace: {{ .Values.namespace.source }}
roleRef:
  kind: ClusterRole
  name: secret-propagator
  apiGroup: rbac.authorization.k8s.io
